# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [22]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    env:
      NEXT_PUBLIC_API_URL_MPP: https://backend-mpp.newus.id/api
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
    - name : Run NPM
      working-directory: ./kiosk-admin
      run: |
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
    - name : Run build
      working-directory: ./kiosk-admin
      run: npm run build --if-present
    - name : change repo
      run : cd /home/newus-admin-kiosk/htdocs/admin-kiosk.newus.id/actions-runner/_work/mpp-admin-kiosk/mpp-admin-kiosk/kiosk-admin
    # - run : pm2 restart mppdigital.newus.id
